// dummyData.js

const dummyData = {
  영화: [
    {
      id: 1,
      title: "베테랑",
      category: ["영화", "코미디", "액션"],
      year: 2015,
      runtime: "123분",
      imgClass: "img_movie_001",
      favoriteRatio: 8.9,
    },
    {
      id: 2,
      title: "공조2:인터내셔날",
      category: ["영화", "코미디", "액션"],
      year: 2022,
      runtime: "128분",
      imgClass: "img_movie_002",
      favoriteRatio: 8.9,
    },
    {
      id: 3,
      title: "천박사 퇴마연구소",
      category: ["영화", "코미디", "호러"],
      year: 2023,
      runtime: "98분",
      imgClass: "img_movie_003",
      favoriteRatio: 8.9,
    },
    {
      id: 4,
      title: "극한직업",
      category: ["영화", "코미디", "어드벤처"],
      year: 2019,
      runtime: "111분",
      imgClass: "img_movie_004",
      favoriteRatio: 8.9,
    },
    {
      id: 5,
      title: "드림",
      category: ["영화", "코미디", "스포츠"],
      year: 2023,
      runtime: "125분",
      imgClass: "img_movie_005",
      favoriteRatio: 8.9,
    },
    {
      id: 6,
      title: "검사외전",
      category: ["영화", "코미디"],
      year: 2016,
      runtime: "126분",
      imgClass: "img_movie_006",
      favoriteRatio: 8.9,
    },
    {
      id: 7,
      title: "싱글인서울",
      category: ["영화", "코미디", "로맨스"],
      year: 2022,
      runtime: "103분",
      imgClass: "img_movie_007",
      favoriteRatio: 8.9,
    },
    {
      id: 8,
      title: "청년경찰",
      category: ["영화", "코미디", "어드벤처"],
      year: 2017,
      runtime: "108분",
      imgClass: "img_movie_008",
      favoriteRatio: 8.9,
    },
    {
      id: 9,
      title: "아빠는딸",
      category: ["영화", "코미디"],
      year: 2017,
      runtime: "114분",
      imgClass: "img_movie_009",
      favoriteRatio: 8.9,
    },
    {
      id: 10,
      title: "은밀하게 위대하게",
      category: ["영화", "코미디", "어드벤처"],
      year: 2013,
      runtime: "124분",
      imgClass: "img_movie_010",
      favoriteRatio: 8.9,
    },
    {
      id: 11,
      title: "댓글부대",
      category: ["영화", "코미디", "스릴러"],
      year: 2024,
      runtime: "109분",
      imgClass: "img_movie_011",
      favoriteRatio: 8.9,
    },
  ],
  애니메이션: [
    {
      id: 1,
      title: "주술회전",
      category: ["애니메이션", "SF 판타지", "액션"],
      year: 2023,
      runtime: "23분",
      imgClass: "img_animation_001",
      favoriteRatio: 9.0,
    },
    {
      id: 2,
      title: "최애의 아이",
      category: ["애니메이션"],
      year: 2024,
      runtime: "24분",
      imgClass: "img_animation_002",
      favoriteRatio: 9.5,
    },
    {
      id: 3,
      title: "나의 히어로 아카데미아",
      category: ["애니메이션", "액션"],
      year: 2024,
      runtime: "24분",
      imgClass: "img_animation_003",
      favoriteRatio: 9.5,
    },
    {
      id: 4,
      title: "약사의 혼잣말",
      category: ["애니메이션", "미스터리", "스릴러"],
      year: 2023,
      runtime: "23분",
      imgClass: "img_animation_004",
      favoriteRatio: 9.5,
    },
    {
      id: 5,
      title: "헌터x헌터",
      category: ["애니메이션", "SF 판타지", "액션"],
      year: 2014,
      runtime: "23분",
      imgClass: "img_animation_005",
      favoriteRatio: 9.5,
    },
    {
      id: 6,
      title: "원피스",
      category: ["애니메이션", "모험", "액션"],
      year: 2009,
      runtime: "25분",
      imgClass: "img_animation_006",
      favoriteRatio: 9.5,
    },
    {
      id: 7,
      title: "괴수 8호",
      category: ["애니메이션", "SF 판타지", "액션"],
      year: 2024,
      runtime: "23분",
      imgClass: "img_animation_007",
      favoriteRatio: 9.5,
    },
    {
      id: 8,
      title: "그대들은 어떻게 살 것인가",
      category: ["애니메이션", "SF 판타지"],
      year: 2023,
      runtime: "124분",
      imgClass: "img_animation_008",
      favoriteRatio: 9.5,
    },
    {
      id: 9,
      title: "귀멸의 칼날",
      category: ["애니메이션", "SF 판타지", "액션"],
      year: 2024,
      runtime: "23분",
      imgClass: "img_animation_009",
      favoriteRatio: 9.5,
    },
    {
      id: 10,
      title: "진격의 거인",
      category: ["애니메이션", "SF 판타지", "액션"],
      year: 2023,
      runtime: "23분",
      imgClass: "img_animation_010",
      favoriteRatio: 9.5,
    },
    {
      id: 11,
      title: "소드 아트 온라인",
      category: ["애니메이션", "SF 판타지", "액션"],
      year: 2019,
      runtime: "23분",
      imgClass: "img_animation_011",
      favoriteRatio: 9.5,
    },
    {
      id: 12,
      title: "나 혼자만 레벨업",
      category: ["애니메이션", "SF 판타지", "액션"],
      year: 2024,
      runtime: "23분",
      imgClass: "img_animation_012",
      favoriteRatio: 9.5,
    },
  ],
  드라마: [
    {
      id: 1,
      title: "슬기로운 의사생활",
      category: ["드라마", "메디컬 시리즈", "코미디"],
      year: 2021,
      runtime: "82분",
      imgClass: "img_drama_001",
      favoriteRatio: 9.1,
    },
    {
      id: 2,
      title: "봄 밤",
      category: ["드라마", "로맨틱"],
      year: 2019,
      runtime: "66분",
      imgClass: "img_drama_002",
      favoriteRatio: 8.4,
    },
    {
      id: 3,
      title: "이번생은 처음이라",
      category: ["드라마", "코미디", "로맨틱"],
      year: 2017,
      runtime: "60분",
      imgClass: "img_drama_003",
      favoriteRatio: 8.4,
    },
    {
      id: 4,
      title: "사내맞선",
      category: ["드라마", "코미디", "로맨틱"],
      year: 2022,
      runtime: "60분",
      imgClass: "img_drama_004",
      favoriteRatio: 8.4,
    },
    {
      id: 5,
      title: "사내맞선",
      category: ["드라마", "코미디", "로맨틱"],
      year: 2021,
      runtime: "62분",
      imgClass: "img_drama_005",
      favoriteRatio: 8.4,
    },
    {
      id: 6,
      title: "그 해 우리는",
      category: ["드라마", "코미디", "로맨틱"],
      year: 2021,
      runtime: "62분",
      imgClass: "img_drama_005",
      favoriteRatio: 8.4,
    },
    {
      id: 7,
      title: "이두나!",
      category: ["드라마", "코미디", "로맨틱"],
      year: 2023,
      runtime: "49분",
      imgClass: "img_drama_007",
      favoriteRatio: 8.4,
    },
    {
      id: 8,
      title: "투투장부주",
      category: ["드라마", "로맨틱"],
      year: 2023,
      runtime: "44분",
      imgClass: "img_drama_008",
      favoriteRatio: 8.4,
    },
    {
      id: 9,
      title: "호텔 델루나",
      category: ["드라마", "로맨틱", "코미디"],
      year: 2019,
      runtime: "73분",
      imgClass: "img_drama_009",
      favoriteRatio: 8.4,
    },
    {
      id: 10,
      title: "별똥별",
      category: ["드라마", "로맨틱", "코미디"],
      year: 2022,
      runtime: "59분",
      imgClass: "img_drama_010",
      favoriteRatio: 8.4,
    },
  ],
  예능: [
    {
      id: 1,
      title: "흑백요리사",
      category: ["예능", "경쟁 리얼리티", "요리"],
      year: 2024,
      runtime: "63분",
      imgClass: "img_entertainment_001",
      favoriteRatio: 9.3,
    },
    {
      id: 2,
      title: "코미디 리벤지",
      category: ["예능", "경쟁 리얼리티", "코미디"],
      year: 2024,
      runtime: "39분",
      imgClass: "img_entertainment_002",
      favoriteRatio: 8.8,
    },
    {
      id: 3,
      title: "코미디 리벤지",
      category: ["예능", "경쟁 리얼리티"],
      year: 2024,
      runtime: "107분",
      imgClass: "img_entertainment_003",
      favoriteRatio: 8.8,
    },
    {
      id: 4,
      title: "생존왕 부족전쟁",
      category: ["예능", "경쟁 리얼리티"],
      year: 2024,
      runtime: "121분",
      imgClass: "img_entertainment_004",
      favoriteRatio: 8.8,
    },
    {
      id: 5,
      title: "솔로지옥",
      category: ["예능", "경쟁 리얼리티"],
      year: 2023,
      runtime: "73분",
      imgClass: "img_entertainment_005",
      favoriteRatio: 8.8,
    },
    {
      id: 6,
      title: "최강야구",
      category: ["예능", "경쟁 리얼리티"],
      year: 2024,
      runtime: "142분",
      imgClass: "img_entertainment_006",
      favoriteRatio: 8.8,
    },
    {
      id: 7,
      title: "지구마불 세계여행",
      category: ["예능", "경쟁 리얼리티", "음식"],
      year: 2023,
      runtime: "89분",
      imgClass: "img_entertainment_007",
      favoriteRatio: 8.8,
    },
    {
      id: 8,
      title: "골때리는 그녀들",
      category: ["예능", "경쟁 리얼리티", "스포츠"],
      year: 2024,
      runtime: "101분",
      imgClass: "img_entertainment_008",
      favoriteRatio: 8.8,
    },
    {
      id: 9,
      title: "더 인플루언서",
      category: ["예능", "경쟁 리얼리티"],
      year: 2024,
      runtime: "81분",
      imgClass: "img_entertainment_009",
      favoriteRatio: 8.8,
    },
    {
      id: 10,
      title: "연애 실험: 블라인드 러브",
      category: ["예능", "경쟁 리얼리티"],
      year: 2024,
      runtime: "56분",
      imgClass: "img_entertainment_010",
      favoriteRatio: 8.8,
    },
    {
      id: 11,
      title: "코미디 로얄",
      category: ["예능", "경쟁 리얼리티", "코미디"],
      year: 2023,
      runtime: "28분",
      imgClass: "img_entertainment_011",
      favoriteRatio: 8.8,
    },
    // 추가 예능 데이터...
  ],
};

export default dummyData;
